title: Theme Test
description: Experiments with Jekyll, Minima, and interactive charts
author: Chris Seeger

# Theme
theme: minima

minima:
  skin: classic

# Project site settings
url: "https://cjseeger.github.io"
baseurl: "/themeTest"

# Show pages in the header
header_pages:
  - index.html
  - results.html
  - blog.html
  - tags.html
  - about.md

# Blog / posts settings
show_excerpts: true

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social:
  name: Chris Seeger
  links:
    - https://github.com/cjseeger
    - https://www.linkedin.com/in/christopher-j-seeger/

