title: Theme Test
description: Experiments with Jekyll, Minima, and interactive charts
author: Chris Seeger

# Theme
theme: minima

# Project site settings
url: "https://cjseeger.github.io"
baseurl: "/themeTest"

# Show pages in the header
header_pages:
  - index.html
  - results.html
    - blog.html
  - about.md

# Blog / posts settings
# show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
