title: Theme Test
description: Testing the Jekyll Minima theme on GitHub Pages
author: Chris Seeger

theme: minima

# Project site settings
url: "https://cjseeger.github.io"
baseurl: "/themeTest"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.html
  - charts.html
  - about.md

